name: Golang build

on: [push] # mss moet dit main zijn 

# These variables can be reused in the build steps
env:
  GOLANG_VERSION: 1.21.x

jobs:
  build:
    runs-on: ubuntu-latest
    # Code Build steps
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Build
        run: go build -o ../bin/workshop -v ./...
        working-directory: workshop-service

      - name: Upload /bin folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workshop
          path: bin/
          retention-days: 1


  docker: 
    needs: build 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: workshop
          path: ./bin

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true